version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://prisma:${DB_PASSWORD}@db:5432/notesdb?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=notesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
